#!/usr/bin/ruby
require 'discordrb'
require 'daemonite'

def voice_commands(bot)
  commands = []
  Dir[File.join(__dir__,'*.pcm')].each do |f|
    name = File.basename(f,'.pcm')
    commands << name.to_sym
    bot.command(name.to_sym) do |event|
      voice_bot = event.voice
      voice_bot.play(File.open(f)) if voice_bot
    end
  end
  commands
end

Daemonite.new do
  on startup do |opts|
    opts[:bot] = Discordrb::Commands::CommandBot.new token: File.read(File.join(__dir__,'token')).strip, prefix: '!'
    commands = voice_commands opts[:bot]

    opts[:bot].command(:connect) do |event|
      channel = event.user.voice_channel
      next "You're not in any voice channel!" unless channel
      opts[:bot].voice_connect(channel)
      event.respond "Connected to voice channel: #{channel.name}"
    end
    opts[:bot].command(:disconnect) do |event|
      channel = event.user.voice_channel
      next "You're not in any voice channel!" unless channel
      opts[:bot].voice_destroy(event.user.server)
    end

    opts[:bot].command(:reload) do |event|
      commands.each do |c|
        opts[:bot].remove_command c
      end
      commands = voice_commands opts[:bot]
      "Available commands: #{commands.join(', ')}"
    end

    opts[:bot].command(:stop) do |event|
      voice_bot = event.voice
      voice_bot.stop_playing if voice_bot
    end

    opts[:bot].command(:ping) do |event|
      event.respond 'Pong!'
    end
  end
  run do |opts|
    opts[:bot].run
  end
  on exit do |opts|
    opts[:bot].stop
    opts[:bot].join
  end
end.go!
